# Generated by Django 5.1.7 on 2025-03-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('flag', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=20)),
                ('emblem', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('tla', models.CharField(max_length=3)),
                ('crest', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_matchday', models.IntegerField()),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons_won', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('utc_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('TIMED', "À l'heure"), ('IN_PLAY', 'En cours'), ('PAUSED', 'En pause'), ('FINISHED', 'Terminé'), ('POSTPONED', 'Reporté'), ('SUSPENDED', 'Suspendu'), ('CANCELED', 'Annulé')], max_length=20)),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(max_length=50)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField()),
                ('score_winner', models.CharField(blank=True, choices=[('HOME_TEAM', 'Équipe à domicile'), ('AWAY_TEAM', "Équipe à l'extérieur"), ('DRAW', 'Match nul')], max_length=20, null=True)),
                ('score_duration', models.CharField(blank=True, choices=[('REGULAR', 'Temps réglementaire'), ('EXTRA_TIME', 'Prolongations'), ('PENALTY_SHOOTOUT', 'Tirs au but')], max_length=20, null=True)),
                ('fulltime_home', models.IntegerField(blank=True, null=True)),
                ('fulltime_away', models.IntegerField(blank=True, null=True)),
                ('halftime_home', models.IntegerField(blank=True, null=True)),
                ('halftime_away', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.area')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.competition')),
                ('referees', models.ManyToManyField(blank=True, related_name='matches', to='api.referee')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team')),
            ],
        ),
    ]
