# Generated by Django 5.1.7 on 2025-03-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_area_competition_referee_team_season_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_key', models.CharField(max_length=10, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('country_iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('country_logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Livescore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=20, unique=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_home_team', models.CharField(max_length=100)),
                ('home_team_key', models.CharField(max_length=20)),
                ('event_away_team', models.CharField(max_length=100)),
                ('away_team_key', models.CharField(max_length=20)),
                ('event_halftime_result', models.CharField(max_length=10)),
                ('event_final_result', models.CharField(max_length=10)),
                ('event_status', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('league_name', models.CharField(max_length=100)),
                ('league_key', models.CharField(max_length=20)),
                ('league_round', models.CharField(max_length=50)),
                ('event_stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('event_referee', models.CharField(blank=True, max_length=100, null=True)),
                ('event_live', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_place', models.CharField(max_length=10)),
                ('standing_place_type', models.CharField(blank=True, max_length=100, null=True)),
                ('standing_team', models.CharField(max_length=100)),
                ('standing_P', models.CharField(max_length=10)),
                ('standing_W', models.CharField(max_length=10)),
                ('standing_D', models.CharField(max_length=10)),
                ('standing_L', models.CharField(max_length=10)),
                ('standing_F', models.CharField(max_length=10)),
                ('standing_A', models.CharField(max_length=10)),
                ('standing_GD', models.CharField(max_length=10)),
                ('standing_PTS', models.CharField(max_length=10)),
                ('team_key', models.CharField(max_length=20)),
                ('league_key', models.CharField(max_length=20)),
                ('league_season', models.CharField(max_length=20)),
                ('league_round', models.CharField(blank=True, max_length=20, null=True)),
                ('standing_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='area',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='referees',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='season',
            name='winner',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='crest',
        ),
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tla',
        ),
        migrations.AddField(
            model_name='team',
            name='team_key',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(max_length=20, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('player_number', models.CharField(blank=True, max_length=10, null=True)),
                ('player_country', models.CharField(blank=True, max_length=100, null=True)),
                ('player_type', models.CharField(max_length=50)),
                ('player_age', models.CharField(blank=True, max_length=10, null=True)),
                ('player_match_played', models.CharField(blank=True, max_length=10, null=True)),
                ('player_goals', models.CharField(blank=True, max_length=10, null=True)),
                ('player_yellow_cards', models.CharField(blank=True, max_length=10, null=True)),
                ('player_red_cards', models.CharField(blank=True, max_length=10, null=True)),
                ('player_image', models.URLField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
