# Generated by Django 5.1.7 on 2025-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_country_livescore_standing_remove_match_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
