# Generated by Django 5.1.7 on 2025-03-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_country_country_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Livescore',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='Standing',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
